services:
  windows:
    image: dockurr/windows
    container_name: windows-dev
    environment:
      KVM: "N"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      VERSION: "11"
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./:/shared
    stop_grace_period: 2m
    restart: on-failure
